name: Zeek matrix tests

on:
  push:
  pull_request:

jobs:
  test:
    name: test-${{ matrix.zeekver }}
    runs-on: ubuntu-latest
    # Don't run twice when pushing to PRs
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      fail-fast: false
      matrix:
        zeekver: [zeek, zeek-lts, zeek-nightly]
    steps:
    - uses: actions/checkout@v4
    - uses: zeek/action-zkg-install@v2
      with:
        zeek_version: ${{ matrix.zeekver }}
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: zkg-logs-${{ matrix.zeekver }}
        path: ${{ github.workspace }}/.action-zkg-install/artifacts
