exclude: .*/Baseline

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/maxwinterstein/shfmt-py
  rev: v3.7.0.1
  hooks:
  - id: shfmt
    args: [-w, -i, '4', -ci]

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.2
  hooks:
  - id: ruff-format
  - id: ruff
    args: [--fix]

- repo: local
  hooks:
  - id: stray_baselines
    name: Check for stray BTest baselines
    entry: ./tests/scripts/stray_baselines.py
    language: python
    pass_filenames: false
    additional_dependencies:
    - btest

- repo: https://github.com/crate-ci/typos
  rev: v1.24.3
  hooks:
  - id: typos
