exclude: .*/Baseline

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/maxwinterstein/shfmt-py
  rev: v3.7.0.1
  hooks:
  - id: shfmt
    args: [-w, -i, '4', -ci]

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck

- repo: https://github.com/PyCQA/pylint.git
  rev: v3.2.7
  hooks:
  - id: pylint
    additional_dependencies:
    - zkg

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
  - id: black

- repo: https://github.com/asottile/pyupgrade
  rev: v3.17.0
  hooks:
  - id: pyupgrade
    args: [--py37-plus]

- repo: local
  hooks:
  - id: stray_baselines
    name: Check for stray BTest baselines
    entry: ./tests/scripts/stray_baselines.py
    language: python
    pass_filenames: false
    additional_dependencies:
    - btest
  - id: vermin
    name: Check minimal required Python version
    # Minimal required Python version according to
    # https://docs.zeek.org/en/master/install.html#required-dependencies.
    # The value should be kept consistent with `py-version` in `.pylintrc`.
    entry: vermin -vv --target=3.7- .
    language: python
    pass_filenames: false
    additional_dependencies:
    - vermin

- repo: https://github.com/crate-ci/typos
  rev: v1.24.3
  hooks:
  - id: typos
