#! /usr/bin/env bash
# Git wrapper script for use during testing.

# Unsetting the following prevents git from reading ~/.gitconfig,
# including potential githooks.
export HOME=
export XDG_CONFIG_HOME=

git -c init.defaultBranch=master \
    -c protocol.file.allow=always \
    -c user.name=zkg \
    -c user.email=zkg@zeek.org \
    "$@"
